/* Platform: node type registry.
 * NODE_DEFINITIONS describes available node types (legacy + new).
 * NodeRegistry.get(type) accepts both new dotted types and legacy short names.
 */

export const LIBAI_PROJECT_ID = "local-default";

export const NODE_DEFINITIONS = [
  {
    type: "text.note",
    legacyType: "text",
    title: "文本节点",
    category: "text",
    inputs: [],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: {},
    executor: "text_passthrough",
    panel: "TextNodePanel",
  },
  {
    type: "text.reason",
    legacyType: "text",
    title: "文本推理",
    category: "text",
    inputs: ["text", "image"],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: { provider: "newapi" },
    executor: "text_reason_executor",
    panel: "TextReasonPanel",
  },
  {
    type: "inference.generate",
    legacyType: "text",
    title: "通用推理",
    category: "utility",
    inputs: ["text", "image", "video", "audio"],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: { provider: "newapi" },
    executor: "inference_generate_executor",
    panel: "InferenceGeneratePanel",
  },
  {
    type: "prompt.runner",
    legacyType: "prompt-runner",
    title: "提示词调用",
    category: "utility",
    inputs: ["text", "image", "video", "audio"],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: { provider: "newapi" },
    executor: "inference_generate_executor",
    panel: "PromptRunnerPanel",
  },
  {
    type: "image.input",
    legacyType: "image",
    title: "图片输入",
    category: "image",
    inputs: ["image"],
    outputs: ["image"],
    paramsSchema: {},
    defaultParams: {},
    executor: "asset_passthrough",
    panel: "ImageNodePanel",
  },
  {
    type: "image.generate",
    legacyType: "image",
    title: "图片生成",
    category: "image",
    inputs: ["text", "image"],
    outputs: ["image"],
    paramsSchema: {},
    defaultParams: { provider: "newapi", ratio: "16:9" },
    executor: "image_generate_executor",
    panel: "ImageGeneratePanel",
  },
  {
    type: "asset.generate",
    legacyType: "asset-gen",
    title: "资产生成",
    category: "image",
    inputs: ["image", "text"],
    outputs: ["image"],
    paramsSchema: {},
    defaultParams: {
      provider: "newapi",
      style: "realistic_cinematic",
      assetType: "character_3view",
      ratio: "1:1",
      resolution: "2K",
    },
    executor: "image_generate_executor",
    panel: "AssetGeneratePanel",
  },
  {
    type: "video.generate",
    legacyType: "video",
    title: "视频生成",
    category: "video",
    inputs: ["text", "image", "video"],
    outputs: ["video"],
    paramsSchema: {},
    defaultParams: { provider: "newapi", duration: 5 },
    executor: "video_generate_executor",
    panel: "VideoGeneratePanel",
  },
  {
    type: "audio.input",
    legacyType: "audio",
    title: "音频输入",
    category: "audio",
    inputs: ["audio"],
    outputs: ["audio"],
    paramsSchema: {},
    defaultParams: {},
    executor: "asset_passthrough",
    panel: "AudioNodePanel",
  },
  {
    type: "audio.generate",
    legacyType: "audio",
    title: "音频生成",
    category: "audio",
    inputs: ["text", "audio"],
    outputs: ["audio"],
    paramsSchema: {},
    defaultParams: { provider: "newapi" },
    executor: "audio_generate_executor",
    panel: "AudioGeneratePanel",
  },
  {
    type: "script.storyboard",
    legacyType: "script",
    title: "分镜脚本",
    category: "text",
    inputs: ["text", "image"],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: {},
    executor: "script_storyboard_executor",
    panel: "StoryboardPanel",
  },
  {
    type: "panorama.generate",
    legacyType: "vr720-gen",
    title: "720空间场景",
    category: "image",
    inputs: ["image"],
    outputs: ["image"],
    paramsSchema: {},
    defaultParams: { provider: "newapi", ratio: "16:9", style: "realistic_cinematic" },
    executor: "panorama_image_generate_executor",
    panel: "VR720GenPanel",
  },
  {
    type: "panorama.viewer",
    legacyType: "panorama-viewer",
    title: "720全景预览",
    category: "image",
    inputs: ["image"],
    outputs: ["image"],
    paramsSchema: {},
    defaultParams: {},
    executor: "panorama_viewer_local",
    panel: "PanoramaViewerPanel",
  },
  {
    type: "stage.director",
    legacyType: "director-stage",
    title: "旧版720工作台",
    category: "utility",
    inputs: ["image"],
    outputs: ["text", "image"],
    paramsSchema: {},
    defaultParams: {},
    executor: "director_stage_local",
    panel: "DirectorStageWorkbench",
  },
  {
    type: "jianying.export",
    legacyType: "jianying-export",
    title: "剪映导出",
    category: "utility",
    inputs: ["video", "image", "audio", "text"],
    outputs: ["text"],
    paramsSchema: {},
    defaultParams: { draftName: "分镜草稿" },
    executor: "jianying_draft_export",
    panel: "JianyingExportPanel",
  },
  {
    type: "storyboard.collector",
    legacyType: "storyboard-collector-detail",
    title: "分镜收集细节",
    category: "utility",
    inputs: ["video", "image", "audio"],
    outputs: ["video", "image", "audio"],
    paramsSchema: {},
    defaultParams: { items: [] },
    executor: "storyboard_collector_local",
    panel: "StoryboardCollectorPanel",
  },
];

export const NodeRegistry = {
  all() {
    return NODE_DEFINITIONS;
  },
  get(type) {
    return NODE_DEFINITIONS.find((def) => def.type === type || def.legacyType === type) || null;
  },
  async refresh() {
    if (!window.libai?.registry?.nodes) return { nodes: NODE_DEFINITIONS, providers: [] };
    return window.libai.registry.nodes();
  },
};
